/** Chinese translations of the interface text CodeMirror and its packages render (search, folding, lint, completion, LSP, merge). */
export const chinesePhrases: Readonly<Record<string, string>> = {
  'Find': '查找',
  'Replace': '替换',
  'next': '下一个',
  'previous': '上一个',
  'all': '全部',
  'match case': '区分大小写',
  'regexp': '正则表达式',
  'by word': '全字匹配',
  'replace': '替换',
  'replace all': '全部替换',
  'close': '关闭',
  'current match': '当前匹配',
  'replaced $ matches': '已替换 $ 处',
  'replaced match on line $': '已替换第 $ 行的匹配',
  'on line': '位于行',
  'Go to line': '转到行',
  'go': '转到',
  'Fold line': '折叠',
  'Unfold line': '展开',
  'Folded lines': '已折叠的行',
  'Unfolded lines': '已展开的行',
  'folded code': '已折叠的代码',
  'unfold': '展开',
  'to': '至',
  'Diagnostics': '诊断',
  'No diagnostics': '没有诊断',
  'Completions': '补全',
  'Control character': '控制字符',
  'Selection deleted': '已删除选中内容',
  'New name': '新名称',
  'rename': '重命名',
  'Reference list': '引用列表',
  'Accept': '接受',
  'Reject': '拒绝',
  'Revert this chunk': '还原此处更改',
  '$ unchanged lines': '$ 行未更改',
}
