/** Metadata for navigation; tool implementations are loaded only on demand. */
window.ICE_SKY_TOOLS = [
  {
    "id": "injectiongenerator",
    "name": "注入生成器",
    "title": "本地提示词注入生成器",
    "icon": "fa-dice",
    "order": 0,
    "hidden": false,
    "enabled": true,
    "className": "InjectionGeneratorTool",
    "script": "js/tools/InjectionGeneratorTool.js",
    "template": "templates/injectiongenerator.html"
  },
  {
    "id": "transforms",
    "name": "文本变换",
    "title": "文本变换",
    "icon": "fa-font",
    "order": 1,
    "hidden": false,
    "enabled": true,
    "className": "TransformTool",
    "script": "js/tools/TransformTool.js",
    "template": "templates/transforms.html"
  },
  {
    "id": "samplebuilder",
    "name": "样本构造",
    "title": "样本构造",
    "icon": "fa-layer-group",
    "order": 2.5,
    "hidden": false,
    "enabled": true,
    "className": "SampleBuilderTool",
    "script": "js/tools/SampleBuilderTool.js",
    "template": "templates/samplebuilder.html"
  },
  {
    "id": "steganography",
    "name": "Emoji",
    "title": "Emoji插入",
    "icon": "fa-smile",
    "order": 3,
    "hidden": false,
    "enabled": true,
    "className": "EmojiTool",
    "script": "js/tools/EmojiTool.js",
    "template": "templates/steganography.html"
  },
  {
    "id": "tokenade",
    "name": "资源消耗",
    "title": "资源消耗",
    "icon": "fa-bomb",
    "order": 4,
    "hidden": false,
    "enabled": true,
    "className": "TokenadeTool",
    "script": "js/tools/TokenadeTool.js",
    "template": "templates/tokenade.html"
  },
  {
    "id": "fuzzer",
    "name": "输入扰动",
    "title": "输入扰动",
    "icon": "fa-bug",
    "order": 5,
    "hidden": false,
    "enabled": true,
    "className": "MutationTool",
    "script": "js/tools/MutationTool.js",
    "template": "templates/fuzzer.html"
  },
  {
    "id": "tokenizer",
    "name": "Token可视化",
    "title": "Token可视化",
    "icon": "fa-layer-group",
    "order": 6,
    "hidden": false,
    "enabled": true,
    "className": "TokenizerTool",
    "script": "js/tools/TokenizerTool.js",
    "template": "templates/tokenizer.html"
  },
  {
    "id": "gibberish",
    "name": "乱码",
    "title": "乱码",
    "icon": "fa-comments",
    "order": 7,
    "hidden": false,
    "enabled": true,
    "className": "GibberishTool",
    "script": "js/tools/GibberishTool.js",
    "template": "templates/gibberish.html"
  },
  {
    "id": "bijection",
    "name": "字符映射",
    "title": "字符映射",
    "icon": "fa-right-left",
    "order": 8,
    "hidden": false,
    "enabled": true,
    "className": "BijectionTool",
    "script": "js/tools/BijectionTool.js",
    "template": "templates/bijection.html"
  },
  {
    "id": "splitter",
    "name": "文本拆分",
    "title": "文本拆分",
    "icon": "fa-grip-lines",
    "order": 9,
    "hidden": false,
    "enabled": true,
    "className": "SplitterTool",
    "script": "js/tools/SplitterTool.js",
    "template": "templates/splitter.html"
  },
  {
    "id": "decoder",
    "name": "解码",
    "title": "解码",
    "icon": "fa-key",
    "order": 10,
    "hidden": false,
    "enabled": true,
    "className": "DecodeTool",
    "script": "js/tools/DecodeTool.js",
    "template": "templates/decoder.html"
  },
  {
    "id": "promptcraft",
    "name": "AI改写",
    "title": "AI改写",
    "icon": "fa-wand-magic-sparkles",
    "order": 11,
    "hidden": false,
    "enabled": true,
    "className": "PromptCraftTool",
    "script": "js/tools/PromptCraftTool.js",
    "template": "templates/promptcraft.html"
  },
  {
    "id": "stylecraft",
    "name": "古风写作",
    "title": "古风写作",
    "icon": "fa-feather-alt",
    "order": 11.5,
    "hidden": false,
    "enabled": true,
    "className": "StyleCraftTool",
    "script": "js/tools/StyleCraftTool.js",
    "template": "templates/stylecraft.html"
  },
  {
    "id": "translate",
    "name": "AI翻译",
    "title": "AI翻译",
    "icon": "fa-language",
    "order": 12,
    "hidden": true,
    "enabled": true,
    "className": "TranslateTool",
    "script": "js/tools/TranslateTool.js",
    "template": null
  },
  {
    "id": "dialogtemplate",
    "name": "多轮模板",
    "title": "多轮对话模板",
    "icon": "fa-comments",
    "order": 12.4,
    "hidden": false,
    "enabled": true,
    "className": "DialogTemplateTool",
    "script": "js/tools/DialogTemplateTool.js",
    "template": "templates/dialogtemplate.html"
  },
  {
    "id": "asciismuggler",
    "name": "Ascii走私",
    "title": "Ascii走私",
    "icon": "fa-user-secret",
    "order": 14,
    "hidden": false,
    "enabled": true,
    "className": "AsciiSmugglerTool",
    "script": "js/tools/AsciiSmugglerTool.js",
    "template": "templates/asciismuggler.html"
  },
  {
    "id": "imageinject",
    "name": "图像注入",
    "title": "图像注入",
    "icon": "fa-crosshairs",
    "order": 14.5,
    "hidden": false,
    "enabled": true,
    "className": "ImageInjectTool",
    "script": "js/tools/ImageInjectTool.js",
    "template": "templates/imageinject.html"
  },
  {
    "id": "audioinject",
    "name": "音频注入",
    "title": "音频注入",
    "icon": "fa-wave-square",
    "order": 14.75,
    "hidden": false,
    "enabled": true,
    "className": "AudioInjectTool",
    "script": "js/tools/AudioInjectTool.js",
    "template": "templates/audioinject.html"
  },
  {
    "id": "richtextinject",
    "name": "富文本注入",
    "title": "富文本注入",
    "icon": "fa-file-code",
    "order": 14.8,
    "hidden": false,
    "enabled": true,
    "className": "RichTextInjectTool",
    "script": "js/tools/RichTextInjectTool.js",
    "template": "templates/richtextinject.html"
  },
  {
    "id": "docxinject",
    "name": "DOCX注入",
    "title": "DOCX注入",
    "icon": "fa-file-word",
    "order": 14.9,
    "hidden": false,
    "enabled": true,
    "className": "DocxInjectTool",
    "script": "js/tools/DocxInjectTool.js",
    "template": "templates/docxinject.html"
  },
  {
    "id": "pdfinject",
    "name": "PDF注入",
    "title": "PDF注入",
    "icon": "fa-file-pdf",
    "order": 15,
    "hidden": false,
    "enabled": true,
    "className": "PdfInjectTool",
    "script": "js/tools/PdfInjectTool.js",
    "template": "templates/pdfinject.html"
  },
  {
    "id": "pitaxonomy",
    "name": "注入技术",
    "title": "注入技术",
    "icon": "fa-sitemap",
    "order": 16,
    "hidden": false,
    "enabled": true,
    "className": "PromptInjectionTaxonomyTool",
    "script": "js/tools/PromptInjectionTaxonomyTool.js",
    "template": "templates/pitaxonomy.html"
  },
  {
    "id": "jailbreaklibrary",
    "name": "破限库",
    "title": "编程模型提示词与 GitHub 仓库",
    "icon": "fa-book",
    "order": 16.1,
    "hidden": false,
    "enabled": true,
    "className": "JailbreakLibraryTool",
    "script": "js/tools/JailbreakLibraryTool.js",
    "template": "templates/jailbreaklibrary.html"
  }
];
