/** Exact text-diff rendering shared by the workbench tools. */
globalThis.IceSkyDiffMethods = {
escapeHtml:t=>String(t).replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;").replace(/'/g,"&#39;"),
tokenizeDiffUnits(t,e="coarse"){const i=String(t||"");return i?"fine"===e?Array.from(i):i.match(/[\p{L}\p{N}_]+|\s+|[^\s]/gu)||[]:[]},
mergeDiffOps(t){const e=[];return t.forEach(t=>{if(!t.tokens||!t.tokens.length)return;const i=e[e.length-1];i&&i.type===t.type?i.tokens=i.tokens.concat(t.tokens):e.push({type:t.type,tokens:t.tokens.slice()})}),e},
prefixSuffixDiff(t,e){let i=0,s=t.length-1,n=e.length-1;for(;i<=s&&i<=n&&t[i]===e[i];)i+=1;for(;s>=i&&n>=i&&t[s]===e[n];)s-=1,n-=1;const r=[];return i>0&&r.push({type:"equal",tokens:t.slice(0,i)}),s>=i&&r.push({type:"delete",tokens:t.slice(i,s+1)}),n>=i&&r.push({type:"insert",tokens:e.slice(i,n+1)}),s+1<t.length&&r.push({type:"equal",tokens:t.slice(s+1)}),this.mergeDiffOps(r)},
computeSequenceDiff(t,e,i=9e4){if(!t.length&&!e.length)return[];if(!t.length)return[{type:"insert",tokens:e.slice()}];if(!e.length)return[{type:"delete",tokens:t.slice()}];if(t.length*e.length>i)return this.prefixSuffixDiff(t,e);const s=Array.from({length:t.length+1},()=>new Uint32Array(e.length+1));for(let i=t.length-1;i>=0;i-=1)for(let n=e.length-1;n>=0;n-=1)s[i][n]=t[i]===e[n]?s[i+1][n+1]+1:Math.max(s[i+1][n],s[i][n+1]);const n=[];let r=0,u=0;for(;r<t.length&&u<e.length;)t[r]===e[u]?(n.push({type:"equal",tokens:[t[r]]}),r+=1,u+=1):s[r+1][u]>=s[r][u+1]?(n.push({type:"delete",tokens:[t[r]]}),r+=1):(n.push({type:"insert",tokens:[e[u]]}),u+=1);for(;r<t.length;)n.push({type:"delete",tokens:[t[r]]}),r+=1;for(;u<e.length;)n.push({type:"insert",tokens:[e[u]]}),u+=1;return this.mergeDiffOps(n)},
renderSimpleDiffOps(t){let e="",i="",s=0,n="",r="";const flushChanged=()=>{(n||r)&&(n&&(e+=`<mark class="fuzzer-diff-removed">${this.escapeHtml(n)}</mark>`),r&&(i+=`<mark class="fuzzer-diff-added">${this.escapeHtml(r)}</mark>`),s+=Math.max(Array.from(n).length,Array.from(r).length,1),n="",r="")};return t.forEach(t=>{const s=t.tokens.join("");if("equal"===t.type){flushChanged();const t=this.escapeHtml(s);e+=t,i+=t}else"delete"===t.type?n+=s:"insert"===t.type&&(r+=s)}),flushChanged(),{sourceHtml:e,outputHtml:i,changedCount:s}},
refineChangedBlock(t,e){const i=String(t||""),s=String(e||"");if(!i&&!s)return{sourceHtml:"",outputHtml:"",changedCount:0};if(!i||!s)return this.renderSimpleDiffOps([{type:i?"delete":"insert",tokens:Array.from(i||s)}]);const n=this.computeSequenceDiff(this.tokenizeDiffUnits(i,"fine"),this.tokenizeDiffUnits(s,"fine"),26e3);return this.renderSimpleDiffOps(n)},
buildDiffMarkup(t,e){const i=this.computeSequenceDiff(this.tokenizeDiffUnits(t,"coarse"),this.tokenizeDiffUnits(e,"coarse"),12e4);let s="",n="",r=0,u="",a="";const flushChanged=()=>{if(!u&&!a)return;const t=this.refineChangedBlock(u,a);s+=t.sourceHtml,n+=t.outputHtml,r+=t.changedCount,u="",a=""};return i.forEach(t=>{const e=t.tokens.join("");if("equal"===t.type){flushChanged();const t=this.escapeHtml(e);s+=t,n+=t}else"delete"===t.type?u+=e:"insert"===t.type&&(a+=e)}),flushChanged(),{sourceHtml:s,outputHtml:n,changedCount:r}}
};
